// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWyVNwH-v9fA0MpOyFzIRa10rl7SYEj5Y',
    appId: '1:512734775360:web:97307f4adf24442e5f37a5',
    messagingSenderId: '512734775360',
    projectId: 'green-expert',
    authDomain: 'green-expert.firebaseapp.com',
    storageBucket: 'green-expert.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Qq9f10-nZgChGzdE9CHRZnF58G4-9X8',
    appId: '1:512734775360:android:9816b02df8e455655f37a5',
    messagingSenderId: '512734775360',
    projectId: 'green-expert',
    storageBucket: 'green-expert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldDXPwwLfcwm48HZwX9pyEEBZeMm08IU',
    appId: '1:512734775360:ios:3a426547b8f1650a5f37a5',
    messagingSenderId: '512734775360',
    projectId: 'green-expert',
    storageBucket: 'green-expert.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldDXPwwLfcwm48HZwX9pyEEBZeMm08IU',
    appId: '1:512734775360:ios:b854be09258576225f37a5',
    messagingSenderId: '512734775360',
    projectId: 'green-expert',
    storageBucket: 'green-expert.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
